### ISSUE TITLE
StatServer config doesnt accept password

### ISSUE THREAD

**Issue by ghost** [LittlePeng/redis-monitor#9]
providing a password for stats server block is unrecognized.

**Comment by ghost** [comment]
See PR above on how I resolved the issue. Feel free to patch accordingly and close if you do not want the scripts executable.

**Comment by LittlePeng** [comment]
👍

**Comment by ghost** [comment]
Still getting more NOAUTH errors:
```
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/tornado/web.py", line 954, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "/root/redis-monitor/src/api/controller/InfoController.py", line 15, in get
        redis_info = self.getStatsPerServer(server)
      File "/root/redis-monitor/src/api/controller/BaseController.py", line 14, in getStatsPerServer
        info = connection.info()
      File "/usr/lib/python2.7/site-packages/redis/client.py", line 760, in info
        return self.execute_command('INFO')
      File "/usr/lib/python2.7/site-packages/redis/client.py", line 668, in execute_command
        return self.parse_response(connection, command_name, **options)
      File "/usr/lib/python2.7/site-packages/redis/client.py", line 680, in parse_response
        response = connection.read_response()
      File "/usr/lib/python2.7/site-packages/redis/connection.py", line 629, in read_response
        raise response
    ResponseError: NOAUTH Authentication required.
```
